### ISSUE TITLE
Great! But what's changing?

### ISSUE THREAD

**Issue by jhabdas** [rangle/redux-segment#11]
Thanks for creating this. Thoughts on including [a change log generator](https://github.com/skywinder/github-changelog-generator) so consumers can quickly grok what's changed?

**Comment by bertrandk** [comment]
Yes, absolutely. The next minor release (expected in the next couple of weeks) should carry a change log.

**Comment by jhabdas** [comment]
Booya. Thanks!

**Comment by bertrandk** [comment]
Re-opening to track ahead of v1.0 release.

**Comment by r-bansal** [comment]
Just looking at a few related items. Something to discuss: use a combination of [semantic-release-cli](https://www.npmjs.com/package/semantic-release-cli) with [commitizen](https://www.npmjs.com/package/commitizen)
