### ISSUE TITLE
Custom mapper mentioned in documentation, but missing in newest release.

### ISSUE THREAD

**Issue by joakimgrr** [rangle/redux-segment#127]
Tried to get a custom mapper working by following the documentation, but it seems that the custom mapper feature is not in the newest release although mentioned in the documentation.

**Comment by otomer** [comment]
Any update regarding the above? 
Version 1.6.2:
https://github.com/rangle/redux-segment/blob/1.6.2/typings/redux-segment.d.ts
Master:
https://github.com/rangle/redux-segment/blob/master/typings/redux-segment.d.ts

**Comment by jcarroll2007** [comment]
I don't know typescript - but it looks like the customOptions are defined here -https://github.com/rangle/redux-segment/blob/1.6.2/src/index.js#L23. Is typescript preventing them from being used?

**Comment by otomer** [comment]
No, it just probably means they forgot to publish it to npm as part of 1.6.2

**Comment by joakimgrr** [comment]
Closing this issue as it seems that this project is no longer maintained.
