### ISSUE TITLE
Webpack Warning

### ISSUE THREAD

**Issue by shantp** [rangle/redux-segment#25]
```
WARNING in ./~/redux-segment/redux-segment.js
Critical dependencies:
1:485-492 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
```

Webpack throws this warning when using redux-segment. Everything works as expected, just FYI.

**Comment by samcorcos** [comment]
+1

This package makes life much easier. Thanks for putting it together.

**Comment by gbrassey** [comment]
You'll want to ignore compiling this in your webpack config until the library addresses it: 

```
module.exports = {
  ...
  module: {
    ...
    noParse: [
      /node_modules\/redux-segment/,
    ],
  },
};
```

**Comment by bertrandk** [comment]
@shantp Would it be possible for you to share your webpack config file with me? While this is a known issue with browserify-ed standalone bundles, none of our internal webpack configs are triggering the warning for me. So while I have a fix, I want to make sure the warning really goes away.

**Comment by shantp** [comment]
@bertrandk Attached.
[webpack.config.dev.js.zip](https://github.com/rangle/redux-segment/files/219269/webpack.config.dev.js.zip)

**Comment by alexbeletsky** [comment]
I'm experiencing the same issue and actually, it's the first time I see anything like that, among using many other 3rd party libraries with `/dist` transpiled code.

The library still works fine, but I'd like to get rid of the warning. The solution from @gbrassey looks fine, but can we solve that in a first place?

There is something similar, that I recently did here,

https://github.com/kimmobrunfeldt/react-progressbar.js/pull/6

The thing is to [transform module to UMD](https://github.com/kimmobrunfeldt/react-progressbar.js/pull/6/commits/5c7beb7f776c56493f2f5d1ccec62f05348a218d#diff-e56633f72ecc521128b3db6586074d2cR3), as I tried it with another library, webpack loads it without any warnings.

Should we try same approach here?

**Comment by alexbeletsky** [comment]
I tried it here, quickly

https://github.com/blogfoster/redux-segment/commit/b3134ff449f9ce9733f2ba54eff17246facb187c

Event with "transform-es2015-modules-umd", webpack still makes a warning. It looks like it's due to fact the way browserify does it transformations.

**Comment by bertrandk** [comment]
@alexbeletsky It looks like the root cause here is an [old issue](https://github.com/webpack/webpack/issues/319). I'm just moving the build system to use babel. A test build is in production right now and it looks good so far...just tweaking things to resolve #28 before cutting an official build.

**Comment by DerekStrickland** [comment]
+1

adding so I'll get notified of resolution.  No need to respond.

**Comment by alexbeletsky** [comment]
@bertrandk any updates on this issue? Not that critical, but very annoying to see that warning all the time :)

**Comment by benigeri** [comment]
so I get notified

**Comment by coopermaruyama** [comment]
+1

**Comment by morenoh149** [comment]
@benigeri @coopermaruyama https://help.github.com/articles/subscribing-to-conversations/
