### ISSUE TITLE
Missing payload

### ISSUE THREAD

**Issue by iolloyd** [rangle/redux-segment#29]
As per the docs, I've added a payload in the following manner:

```json
meta: {
  analytics: {
    eventType: EventTypes.track,
    eventPayload: {
      name: SELECT_AGE,
      age: 30
    }
  }
}
...
```
but name and age are not being reported by the segment.com debugger.

**Comment by iolloyd** [comment]
Resolved.

**Comment by r-bansal** [comment]
Just curious - I was looking into this right now, what was the issue?

**Comment by iolloyd** [comment]
The documentation was misleading, so I dug into the code. It didn't specify the correct keys needed for the payload. I added event, names and properties and they now register correctly. I'd be happy to add a PR that better reflects the tests.

**Comment by bertrandk** [comment]
@iolloyd I'd love to take a look at that PR if you have time to make it.

**Comment by morenoh149** [comment]
@iolloyd indeed, how exactly did you add event, names and properties?
I'm seeing an analytics.js POST request happening in my dev tools but the payload is lacking the information I provided.

Here's what I have
```es
export function segmentTrackCheckout (accountId) {
  return {
    type: SEGMENT_CHECKOUT,
    payload: {
      accountId,
    },
    meta: {
      analytics: EventTypes.track,
    },
  };
}
```

**Comment by morenoh149** [comment]
After looking through the source code we were able to make it work as follows
```js
export function segmentTrackCheckoutLinkSMSSent (accountId) {
  return {
    type: SEGMENT_CHECKOUTLINKSMS_SENT,
    meta: {
      analytics: {
        eventType: EventTypes.track,
        eventPayload: {
          event: 'Checkout Link SMS Sent',
          properties: {
            accountId
          }
        }
      }
    },
  };
}
```
