### ISSUE TITLE
cut new release?

### ISSUE THREAD

**Issue by SpainTrain** [rangle/redux-segment#33]
Would it be possible to get a new release cut?  It was pretty confusing discovering that the `customMapper` feature described in the README wasn't actually available in the latest release version.  Thanks!

**Comment by bertrandk** [comment]
@SpainTrain Coming tonight...

**Comment by evanrs** [comment]
So should this issue be closed?

**Comment by SpainTrain** [comment]
nope

```
$ npm info redux-segment version
0.7.2
```

https://github.com/rangle/redux-segment/commits/master

**Comment by brandly** [comment]
should be able to close this now:

```shell
$ npm info redux-segment version
1.2.0
```
