### ISSUE TITLE
Is it a good idea to raise error in tracking library?

### ISSUE THREAD

**Issue by ahmed1490** [rangle/redux-segment#34]
https://github.com/rangle/redux-segment/blob/master/src/event/group.js#L6

Even if tracking fails. The app should continue to function.

It will be a good idea to raise errors only in development or give a function which can register an error callback. For instance window.error as callback

**Comment by julianusti** [comment]
not good at all :)

**Comment by IanMitchell** [comment]
Just ran into this as well :(

**Comment by bertrandk** [comment]
@IanMitchell This is definitely being taken out in the next day or so. Or at the very least, it won't throw outside of DEV.

**Comment by IanMitchell** [comment]
Thanks :)
