### ISSUE TITLE
possibility to override emit 

### ISSUE THREAD

**Issue by ahmed1490** [rangle/redux-segment#35]
```
function emit(type: string, fields: Array) {
  window.analytics && window.analytics[type](...fields);
}
```

Would be useful to specifically use a specific library, inhouse analytics solutions etc.

Since the package is called redux-segment, the default can stay the same though window.analytics

**Comment by bertrandk** [comment]
1.6.0 added support for specifying a custom `client` key. It should work just fine as long as the passed-in lib supports the same interface/function calls (page, event, etc...). Please re-open if you have a broader use-case in mind.
