### ISSUE TITLE
npm package is published without dist files

### ISSUE THREAD

**Issue by chollier** [rangle/redux-segment#47]
It seems to me that the npm package `1.0.0` was published without the `dist` repository which makes this package unusable.

This is more certainly because `npm publish` picks up `.gitignore` when no `.npmignore` is present.
`.gitignore` lists `dist` : https://github.com/rangle/redux-segment/blob/master/.gitignore#L73

**Comment by jspangler** [comment]
+1

**Comment by mattjstar** [comment]
+1

**Comment by alexbeletsky** [comment]
+1 that's the major issue, guys.. I've just upgraded and the build is broken. Would be great it you re-publish.

**Comment by chollier** [comment]
@bertrandk any update on that ? would love to use the lib

**Comment by chollier** [comment]
Solved by df96b10c5bb91e19a89e552f2c8e08c835112d89

**Comment by chollier** [comment]
Thanks @bertrandk :)
