### ISSUE TITLE
Docs issue with custom mapping

### ISSUE THREAD

**Issue by pandaiolo** [rangle/redux-segment#53]
I am using npm version 1.1.0

The docs states:

    const tracker = createTracker(customMapper);

To make it work, I had to instead use: 

    const tracker = createTracker({ mapper: customMapper });

(Seem consistent with the source code)

**Comment by kevinhos** [comment]
Looks like there is a PR to address this https://github.com/rangle/redux-segment/pull/52

**Comment by pandaiolo** [comment]
This issue is solved with merged PR #52
