### ISSUE TITLE
Custom Mapper function with optional analytics?

### ISSUE THREAD

**Issue by IanMitchell** [rangle/redux-segment#69]
Have an issue right now where I have a customMapper set up, but in the function itself I have a condition to determine whether or not to fire analytics. When the condition is false, I do a return but end up with this error (post-Babel): `Uncaught (in promise) TypeError: typeFieldHandlers[type] is not a function`

Is there a way to indicate to redux-segment that there won't be a meta/analytics field to attach and go on to the next action?

**Comment by bertrandk** [comment]
Should be fixed in v1.4.2...please reopen if there's any issues.

**Comment by IanMitchell** [comment]
Thanks! Much appreciated :)
