### ISSUE TITLE
Ability to record multiple events when dispatching one action

### ISSUE THREAD

**Issue by stephenmathieson** [rangle/redux-segment#77]
First off, this library is awesome. We (@segmentio) use this in-house and _love it_! Awhile back, I started building a Redux middleware similar to this and was pleasantly surprised when a friend pointed this out. You guys rock!

Now... I've found that we often want to fire off two `analytics.js` events in a single action. For example, given this chunk of code:

```js
// signup: create a user and a workspace
const { user, workspace } = await api.createUserAndWorkspace(emailAddress)
dispatch({
  type: 'SIGNED_UP', // whatever
  payload: { // arbitrary... stuff the reducer needs
    workspace_id: workspace.id,
    user_id: user.id
  }
})
```

We'd want to track two things:

```js
analytics.identify({ email: emailAddress }) // identify the new user
analytics.track('Workspace Created', { user_id: user.id, workspace_id: workspace.id }) // record the workspace creation
```

Is this something you've incountered? If so, how have you handled it? All of the options I've explored seem more complicated/leaky than just calling `window.analytics.identify()` directly :/

**Comment by bertrandk** [comment]
Great to hear @stephenmathieson. Yup, it's always always been either `identity` or `alias` (for Mixpanel). If you're using 1.4.0+, you should be able to use [the array syntax](https://github.com/rangle/redux-segment#emitting-more-than-one-event). Tonight's 1.5.0 brings equal support for this feature to custom mappers. This will be better documented in the future. 😉

Let me know if this works for your use case.

**Comment by stephenmathieson** [comment]
I can't believe I missed that. Thanks a ton - this is perfect!
