### ISSUE TITLE
#73 breaks server side rendering due to usage of window object

### ISSUE THREAD

**Issue by pandaiolo** [rangle/redux-segment#79]
This trace : 

		13:08:04.000 at Object.<anonymous> (/app/src/util/create-store.js:27:17)
		13:08:04.000 at createTracker (/app/node_modules/redux-segment/dist/index.js:49:70)
		13:08:04.000 at defaultClient (/app/node_modules/redux-segment/dist/event/configuration.js:29:10)
		13:08:04.000 ReferenceError: window is not defined

PR #73 ads a reference to `window` object, which as a consequences breaks server side usage of `redux-segment` alltogether

**Comment by alexandrebini** [comment]
+1 😃
