### ISSUE TITLE
Install with react router redux, getting Cannot read property 'page' of undefined

### ISSUE THREAD

**Issue by ajmajma** [rangle/redux-segment#92]
Unsure what is causing this error - here is my setup, any/all feedback welcome!

```
 // tracker for segment
const tracker = createTracker();
// extend middlewares here
const middlewares = [ tracker];
// services object
const services = {
  api_base: process.env.API_BASE,
};
// transform state from immutable for logging
function stateTransformer(state) {
  return state.toJS();
}

const composed = [applyMiddleware(...middlewares)];
const routerReducerInitialState = new immutable.Map({'locationBeforeTransitions': null});
const immutableRouterReducer = (state = routerReducerInitialState, {type, payload}) => {
  if (type === '@@router/LOCATION_CHANGE') {
    return state.set('locationBeforeTransitions', payload);
  }
  return state;
};

const reducers = combineReducers({
  ...follain.combinedReducers,
  routing: immutableRouterReducer
});

const enhancer = compose(...composed);
const store = createStore(reducers, immutable.Map(), enhancer);
const history = syncHistoryWithStore(browserHistory, store, {
  selectLocationState: state => ({locationBeforeTransitions: state.getIn(['routing', 'locationBeforeTransitions'])})
});
```

perhaps because I am setting up my middlewares as an array? But it does not cause issues with anything else. Looking for some help to get this setup. Thanks!

**Comment by bertrandk** [comment]
@ajmajma Are you always including the segment snippet in index.html or just placing it in production?

**Comment by ajmajma** [comment]
Looks like I was missing it all together, sorry about that! Based on other comments - I downgrade to 1.5.0, then it read back a meaningful error (and didn't break). Sorry for the confusion.

**Comment by bertrandk** [comment]
@ajmajma Ah, no worries. The next version actually restores 1.5 behaviour. It's in master right now and awaiting another patch before release.

**Comment by palnes** [comment]
I'm seeing the same error. Does this mean that I have to have the snippet loaded before any Webpack magic? There is one package, analytics.js-loader, that allows using the loader from an npm package, but it doesn't seem to work with this project. Might be helpful?

**Comment by palnes** [comment]
Nevermind, the setup works, I forgot to put stuff in `window` somewhere along the way in my very bespoke setup.
