### ISSUE TITLE
Cannot read property 'page' of undefined - Jest Test

### ISSUE THREAD

**Issue by paulocesarpcfj** [rangle/redux-segment#94]
Hi!

I'm getting an error when I try to run my test enviroment.
The error seems like 'Cannot read property 'page' of undefined'. When I remove the call of createTracker of my store configuration it runs nicely.

Here's where I try to apply the Tracker at my middleware:

`applyMiddleware(routingMiddleware, thunk, promiseMiddleware(), tracker)`

Could you help me? I've already tried to use the 1.5.0 version like said in another issues, but isn't worked for me.

Kind regards.

**Comment by Geczy** [comment]
+1 here as well. Removing "tracker" fixes this issue

**Comment by zachrnolan** [comment]
Also seeing the same issue. Any updates on this?

**Comment by Geczy** [comment]
Seems like a dead project, might wanna opt for https://github.com/rangle/redux-beacon

**Comment by zachrnolan** [comment]
Thanks for the recommendation @Geczy

**Comment by bertrandk** [comment]
Redux Beacon is a great library. v1.6.2 should also fix some of these issues.
